# Generated by Django 4.2.4 on 2023-09-25 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practisedrf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empolyedata',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
