# Generated by Django 4.2.4 on 2023-09-25 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practisedrf', '0002_alter_empolyedata_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empolyedata',
            old_name='password',
            new_name='cpassword',
        ),
    ]
